
TYPE
	HMIType : 	STRUCT  (*HMI Main type*)
		AutomaticPage : HMIAutomaticPageType;
		ManualPage : HMIManualPageType;
		HeaderContent : HMIHeaderContentType;
		RecipeContent : HMIRecipeContentType;
	END_STRUCT;
	HMIAutomaticPageType : 	STRUCT  (*HMI Interface Output type*)
		StartButtonEnable : BOOL;
		StartButton : BOOL;
		StopButtonVisibility : BOOL;
		InitButtonEnable : BOOL;
		InitButton : BOOL;
		ConveyorSpeed : REAL;
		ConveyorSpeedEnable : BOOL;
		AutoButtonEnable : BOOL;
		AutoButton : BOOL;
		LinkButtonEnable : BOOL;
		LinkButton : BOOL;
		ReadyToStartVisibility : BOOL;
		CurrentCapWorkingTime : UDINT;
		LastCapWorkedTime : UDINT;
		AvgCapWorkTime : UDINT;
		ClearStats : BOOL;
		PuncherIncludedCheckbox : BOOL;
		PuncherIncludedCheckboxEnable : BOOL;
		PuncherOffset : REAL;
		PuncherOffsetEnable : BOOL;
		CapsCounter : UDINT;
		StamperIncludedCheckbox : BOOL;
		StamperIncludedCheckboxEnable : BOOL;
		StamperOffset : REAL;
		StamperOffsetEnable : BOOL;
		RecipesEnable : BOOL;
		ShowLinkMsg : BOOL;
	END_STRUCT;
	HMIManualPageType : 	STRUCT  (*HMI Interface Output type*)
		ManualButtonEnable : BOOL;
		ManualButton : BOOL;
		StopperForwardButtonEnable : BOOL;
		StopperForwardButton : BOOL;
		Lane1ForwardButtonEnable : BOOL;
		Lane1ForwardButton : BOOL;
		Lane2ForwardButtonEnable : BOOL;
		Lane2ForwardButton : BOOL;
		ConveyorHomeButtonEnable : BOOL;
		ConveyorHomeButton : BOOL;
		ConveyorPowerButtonEnable : BOOL;
		ConveyorPowerButton : BOOL;
		ConveyorMoveButtonEnable : BOOL;
		ConveyorMoveButton : BOOL;
		ConveyorSpeed : REAL;
		ConveyorSpeedEnable : BOOL;
		ConveyorAxisHomed : BOOL;
		ConveyorAxisPowered : BOOL;
		PuncherHomeButtonEnable : BOOL;
		PuncherHomeButton : BOOL;
		PuncherPowerButtonEnable : BOOL;
		PuncherPowerButton : BOOL;
		PuncherMoveButtonEnable : BOOL;
		PuncherMoveButton : BOOL;
		PuncherSpeed : REAL;
		PuncherSpeedEnable : BOOL;
		PuncherAxisHomed : BOOL;
		PuncherAxisPowered : BOOL;
		PuncherForwardButtonEnable : BOOL;
		PuncherForwardButton : BOOL;
		PuncherPosition : LREAL;
		PuncherPositionEnable : BOOL;
		ColourSorterInterface : ColourSorterInterfaceType;
		ConveyorInterface : ConveyorInterfaceType;
		PuncherInterface : PuncherInterfaceType;
		ConveyorActSpeed : REAL;
		ConveyorActPosition : LREAL;
		PuncherActSpeed : REAL;
		PuncherActPosition : LREAL;
		ConveyorAcceleration : REAL;
		ConveyorAccelerationEnable : BOOL;
		PuncherAcceleration : REAL;
		PuncherAccelerationEnable : BOOL;
	END_STRUCT;
	HMIHeaderContentType : 	STRUCT  (*HMI Interface Output type*)
		SlaveConnectionOk : BOOL;
		PendingAlarms : STRING[3];
		StateManual : BOOL;
		StateWaitingInit : BOOL;
		StateInitializing : BOOL;
		StateWaitingStart : BOOL;
		StateWaitingModulesReady : BOOL;
		StateWaitingCap : BOOL;
		StatePunchingCap : BOOL;
		StateDeliveringCap : BOOL;
		StateError : BOOL;
		StateWaitModeSelection : BOOL;
		StateSortingCap : BOOL;
		ResetAlarms : BOOL;
	END_STRUCT;
	HMIRecipeContentType : 	STRUCT  (*HMI Interface Output type*)
		EnableRecipesManagement : BOOL;
	END_STRUCT;
END_TYPE
